/* This file was generated by SableCC (http://www.sablecc.org/). */

package musicseeder.node;

import musicseeder.analysis.*;

@SuppressWarnings("nls")
public final class AAllNoteFunction extends PFunction
{

    public AAllNoteFunction()
    {
        // Constructor
    }

    @Override
    public Object clone()
    {
        return new AAllNoteFunction();
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAllNoteFunction(this);
    }

    @Override
    public String toString()
    {
        return "";
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        throw new RuntimeException("Not a child.");
    }
}
