/* This file was generated by SableCC (http://www.sablecc.org/). */

package musicseeder.node;

import musicseeder.analysis.*;

@SuppressWarnings("nls")
public final class AChord extends PChord
{
    private PNote _note_;
    private PFunction _function_;

    public AChord()
    {
        // Constructor
    }

    public AChord(
        @SuppressWarnings("hiding") PNote _note_,
        @SuppressWarnings("hiding") PFunction _function_)
    {
        // Constructor
        setNote(_note_);

        setFunction(_function_);

    }

    @Override
    public Object clone()
    {
        return new AChord(
            cloneNode(this._note_),
            cloneNode(this._function_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAChord(this);
    }

    public PNote getNote()
    {
        return this._note_;
    }

    public void setNote(PNote node)
    {
        if(this._note_ != null)
        {
            this._note_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._note_ = node;
    }

    public PFunction getFunction()
    {
        return this._function_;
    }

    public void setFunction(PFunction node)
    {
        if(this._function_ != null)
        {
            this._function_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._function_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._note_)
            + toString(this._function_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._note_ == child)
        {
            this._note_ = null;
            return;
        }

        if(this._function_ == child)
        {
            this._function_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._note_ == oldChild)
        {
            setNote((PNote) newChild);
            return;
        }

        if(this._function_ == oldChild)
        {
            setFunction((PFunction) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
