/* This file was generated by SableCC (http://www.sablecc.org/). */

package musicseeder.analysis;

import musicseeder.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseStart(Start node);
    void caseASong(ASong node);
    void caseAPart(APart node);
    void caseAChord(AChord node);
    void caseAAllNoteFunction(AAllNoteFunction node);
    void caseATonikaFunction(ATonikaFunction node);
    void caseASubdominantFunction(ASubdominantFunction node);
    void caseADominantFunction(ADominantFunction node);
    void caseATonikaParFunction(ATonikaParFunction node);
    void caseASubdominantParFunction(ASubdominantParFunction node);
    void caseADominantParFunction(ADominantParFunction node);
    void caseAMelody(AMelody node);
    void caseASingleNote(ASingleNote node);
    void caseASplitNote(ASplitNote node);
    void caseAParallelNote(AParallelNote node);
    void caseAStraightDivision(AStraightDivision node);
    void caseAPunktureDivision(APunktureDivision node);

    void caseEOF(EOF node);
}
