/* This file was generated by SableCC (http://www.sablecc.org/). */

package musicseeder.node;

import java.util.*;

import musicseeder.analysis.*;

@SuppressWarnings("nls")
public final class ASong extends PSong
{
    private final NodeList<PPart> _parts_ = new NodeList<PPart>(this);

    public ASong()
    {
        // Constructor
    }

    public ASong(
        @SuppressWarnings("hiding") List<PPart> _parts_)
    {
        // Constructor
        setParts(_parts_);

    }

    @Override
    public Object clone()
    {
        return new ASong(
            cloneList(this._parts_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASong(this);
    }

    public LinkedList<PPart> getParts()
    {
        return this._parts_;
    }

    public void setParts(List<PPart> list)
    {
	if (list == this._parts_)
	{
	    return;
	}
        this._parts_.clear();
        this._parts_.addAll(list);
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._parts_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._parts_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PPart> i = this._parts_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PPart) newChild);
                    return;
                }

                i.remove();
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
